spring.application.name=chat-service
#embedding-service
embedding.service.url=http://localhost:8080
#ollama
#ollama.base.url=http://localhost:8181
# postgresql db
#spring.datasource.url=jdbc:postgresql://45.119.85.112:5432/ragdb
#spring.datasource.username=postgres
#spring.datasource.password=123456#
#spring.datasource.driver-class-name=org.postgresql.Driver
#hibernate.transaction.jta.platform=true
#spring.jta.enabled=true
server.port=8181